### ISSUE TITLE
Get scan detail in an output variable

### ISSUE THREAD

**Issue by mbarre** [anchore/scan-action#169] opened 2022-04-14 02:16 UTC
Hi,

In our workflows, we scan the image, make the workflow fails and generate an issue. It would be very useful if we can get the detail of the analysis in an output variable that we can inject in the issue we just made. 

What do you think about it ?

Thanks.

**Comment by adriens** [comment] 2022-04-14 04:31
Looks a bit like https://github.com/anchore/scan-action/issues/168

**Comment by adriens** [comment] 2022-04-14 04:32
May also be related to https://github.com/anchore/scan-action/issues/162

**Comment by adriens** [comment] 2022-04-14 04:33
Also @mbarre https://github.com/anchore/scan-action/issues/128

**Comment by tgerla** [comment] 2023-02-02 21:53
I'm going to close this since it is a near-duplicate of #162. Please head over there if you are interested in this feature.

**Closed by tgerla** 2023-02-02 21:53 UTC
Labels: enhancement, good first issue
