### ISSUE TITLE
Syft upgrade causes SPDX format specVersion mismatch

### ISSUE THREAD

**Issue by hermankruger** [anchore/scan-action#342] opened 2024-07-16 08:14 UTC
With release https://github.com/anchore/sbom-action/releases/tag/v0.17.0 on the https://github.com/anchore/sbom-action the Syft version was updated, which in turn updated the SPDX format specVersion from 1.5 to 1.6.

If you then invoke the https://github.com/anchore/scan-action with the generated sbom, the `scan-action` then downloads the grype DB for version 1.5 which is incompatible with 1.6 and an error is thrown.

The https://github.com/anchore/scan-action#scanning-an-sbom-file step in the readme won't succeed currently.

**Comment by spiffcs** [comment] 2024-07-16 14:05
@hermankruger do you mean CycloneDX from 1.5 --> 1.6?

SPDX is currently 2.x

Let me try and get this reproduced on my local and see where the error might be occuring for SBOM --> Scan Action with the new releases. 

It might be as easy as updating the config to specify the version of the document you want, but I agree the default flow should "just work"

**Comment by hermankruger** [comment] 2024-07-17 05:48
@spiffcs, thank for the timely feedback.

What has happened is a combination of `anchore/sbom-action@v0` and `anchore/scan-action@v3` failing due to the release introducing an incompatibility between the two (1.5 -> 1.6).

I will now update to `anchore/sbom-action@v0` and `anchore/scan-action@v4` (4 for emphasis) and this should then solve the issue?

From a https://semver.org/ point of view it would be good to bump breaking changes on both, however I do realize bumping 0 (zero) has implications.

**Comment by spiffcs** [comment] 2024-07-18 16:44
@hermankruger Yep! Give those two actions an upgrade to their latest versions.

If you run into any issues still let me know by filling and tagging me on an issue on either repo and I'll take a look

**Comment by willmurphyscode** [comment] 2024-10-05 18:15
I'm closing this because it seems like it doesn't affect the latest versions of the actions. If we've missed something, please let us know.

**Closed by willmurphyscode** 2024-10-05 18:15 UTC
